### ISSUE TITLE
Window does not open

### ISSUE THREAD

**Issue by maxdwit** [testpushpleaseignore/DSP-Mods#1]
Hi!
Good Idea for this mod.

Small Issue:
Window does not open. See:
https://jumpshare.com/v/HEhe1qDrqdWQ4HxuXXUS

Ideas?

**Comment by maxdwit** [comment]
Apparently it took some time for the first time.
Maybe add this to the small info popup?

**Comment by testpushpleaseignore** [comment]
Oh it seems that it only shows the pop up if you are not in build/delete mode. I copied the logic of when to show the window from another mod, but I can review to see if it's something that I can create a setting of (on when to show/hide the pop up).

**Comment by maxdwit** [comment]
Thank you for looking into it
