### ISSUE TITLE
Update of DSP, Version V0.10.28.20856

### ISSUE THREAD

**Issue by HorstdasPferd** [testpushpleaseignore/DSP-Mods#10]
The mod is causing an error with the update: 
![image](https://github.com/testpushpleaseignore/DSP-Mods/assets/154055707/d714bffc-b082-48cf-9d33-b66c98a53e54)

Would be nice to have this awesome mod working again. Thanks!

**Comment by testpushpleaseignore** [comment]
Unfortunately, my computer died recently and am still waiting for my RMA'd parts to be replaced. Hopefully I can provide updates to these mods when I get my computer working again. Thanks for your patience!

**Comment by testpushpleaseignore** [comment]
Finally got my computer back up and running!

I don't seem to be getting the same error right now, but I can keep playing this game for a bit to see if I can recreate it. If you can think of any ideas as to how it might be showing up, then I'll try to test those same sort of things.

**Comment by RogueNull** [comment]
Not sure if any of this info helps, but I'm encountering the same error on an existing save (with other mods) after clicking the button to launch the GUI.
<img src="https://github.com/testpushpleaseignore/DSP-Mods/assets/35264274/b92444b4-93e0-4e4c-99a9-26b8c54fd822" width="200">
![image](https://github.com/testpushpleaseignore/DSP-Mods/assets/35264274/c8136ceb-dc55-4c26-b5a0-89e7f9248ad6)

I tried to isolate the problem by disabling all mods expect BepInEx and starting a new game. I consistently get the same error immediately after skipping the cutscene:
![image](https://github.com/testpushpleaseignore/DSP-Mods/assets/35264274/9bdfc77f-2067-4086-ac59-9989823949d9)

All mods expect BepInEx disabled:
<img src="https://github.com/testpushpleaseignore/DSP-Mods/assets/35264274/de30d5f2-2329-455b-a680-0725715e1b99" width="400">

**Comment by RogueNull** [comment]
After some digging, installing [ModFixerOne](https://dsp.thunderstore.io/package/starfi5h/ModFixerOne/) does fix it. I suspect it is tied to the Translate function [here](https://github.com/testpushpleaseignore/DSP-Mods/blob/main/Power%20Network%20Manager/UI/PowerWindow.cs#L138C2-L138C2), but I don't know enough about DSP modding know the right way to fix it.

**Comment by RogueNull** [comment]
I removed ModFixerOne so I could look into the exact issue more.

After cloning the repo, copying over the DLLs from DSP and the DLLs from BepInEx, and then building `Power_Network_Manager.dll`, the locally built DLL seems to resolve this issue and the mod seems to be working as expected.

Maybe the mod just needs to be re-built with the latest dependencies? Sorry if this isn't helpful, but it resolved the problem on my side at least.

**Comment by testpushpleaseignore** [comment]
Oh ha! Yeah you're totally right, I didn't notice until now that I was running my mod with some newer dependencies from Visual Studio, rather than testing the mod from the store. I can work on getting this packaged and out the door here shortly. Thanks for the catch!

**Comment by testpushpleaseignore** [comment]
Added Power Network Manager 0.0.7 to store
