### ISSUE TITLE
Feature enhancement request

### ISSUE THREAD

**Issue by CageStooge** [testpushpleaseignore/DSP-Mods#2]
Feature request:
I don't know if this is doable, but is there a way we can pull up the window and view other systems? I sometimes notice that power output on a planet is not meeting demand and it would be super helpful to see what is going on in that power network without having to warp a long distance to see what is there, what's running low, etc.

**Comment by testpushpleaseignore** [comment]
Yeah I was thinking of having that functionality eventually, figured that I would get to it once I can improve the current UI by making it a bit cleaner as well as having statistics graphed out.

**Comment by CageStooge** [comment]
Awesome! I had wide spread power outages across 8 planets -- my fault for not paying attention -- and it's been a nightmare to try and resolve them.
