### ISSUE TITLE
Not working with latest version

### ISSUE THREAD

**Issue by Dysonelephant** [testpushpleaseignore/DSP-Mods#3]
Seems like a new mod update is needed. Would be easy to fix?

**Comment by testpushpleaseignore** [comment]
Yeah I can definitely take a look at getting this working again on 7/5 at the earliest, since I won't have access to a computer until then.

Thanks for letting me know that this isn't working!

**Comment by testpushpleaseignore** [comment]
Should have this fixed in v0.0.5
