### ISSUE TITLE
ER: Config option for placement before ores

### ISSUE THREAD

**Issue by 5thHorseman** [testpushpleaseignore/DSP-Mods#4]
I use BetterGlobeMap along with this mod, and that mod's buttons frequently draw over the numbers from this mod. Would it be possible to - perhaps with a config option - place the numbers somewhere else? The obvious place to me would be before the ores so it reads "2/6 Iron Ore" instead of "Iron Ore 2/6"

**Comment by testpushpleaseignore** [comment]
Just released version 1.0.3, where the window will auto-adjust its size to hopefully get the text to fit, but that mod author for BetterGlobeMap may need to make some changes since the icons they've added started shifting around now.
